server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deliveryapp
    username: postgres
    password: 2022
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access:
    key: heruighurighviey84y57yuvhrjhvrhtvrhtvhjr8u4v8njvertvn8ut8veu834uvndjkwe
    expiration-time: 7500000
  refresh:
    key: evjrkhertvuheruth84y574y587yvbrhvjrtvhrjthv3u4895vuntervnjtkejrht89545y
    expiration-time: 2000000

app:
  running: dev
  admin:
    firstName: "MuhammadQodir"
    lastName: "Yusupov"
    phoneNumber: "+998931668648"
    password: "123"
  role:
    admin:
      name: "ADMIN"
      description: "System administrator"
    manager:
      name: "MANAGER"
      description: "System Manager"
    client:
      name: "CLIENT"
      description: "System client"
  sms:
    valid_till: 15
    valid_till_in: "MINUTES"
  images:
    institutions:
      root:
        path: "institutions/"
    products:
      root:
        path: "products/"